version: "3.9"

services:
  user-svc:
    build: ./user_svc
    container_name: user-svc
    env_file: ./user_svc/.env
    volumes:
      - user-data:/data       # stores users.db
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 10s
      retries: 3

  order-svc:
    build: ./order_svc
    container_name: order-svc
    env_file: ./order_svc/.env
    volumes:
      - order-data:/data      # stores orders.db
    ports:
      - "8002:8000"
    depends_on:
      user-svc:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 10s
      retries: 3

volumes:
  user-data:
  order-data:
