apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify-svc
  namespace: quickkart
  labels: { app: notify-svc }
spec:
  replicas: 1
  selector: { matchLabels: { app: notify-svc } }
  template:
    metadata:
      labels: { app: notify-svc }
    spec:
      containers:
      - name: notify-svc
        image: notify-svc:latest
        imagePullPolicy: IfNotPresent
        ports: [{ containerPort: 8010 }]
        env:
        - { name: MAILHOG_HOST, value: mailhog.quickkart.svc.cluster.local }
        readinessProbe: { httpGet: { path: /healthz, port: 8010 }, initialDelaySeconds: 5 }
        livenessProbe:  { httpGet: { path: /healthz, port: 8010 }, initialDelaySeconds: 5 }
