apiVersion: v1
kind: Service
metadata:
  name: notify-svc
  namespace: quickkart
  labels: { app: notify-svc }
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path:   /metrics
    prometheus.io/port:   "8010"
spec:
  selector: { app: notify-svc }
  ports:
  - port: 8010
    targetPort: 8010
