apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-svc
  namespace: quickkart
  labels: { app: order-svc }
spec:
  replicas: 1
  selector: { matchLabels: { app: order-svc } }
  template:
    metadata:
      labels: { app: order-svc }
    spec:
      volumes:
      - name: data
        emptyDir: {}  
      containers:
      - name: order-svc
        image: order-svc:latest
        imagePullPolicy: IfNotPresent
        ports: [{ containerPort: 8000 }]
        volumeMounts:
        - name: data
          mountPath: /data  
        envFrom:
        - configMapRef: { name: order-svc-env }
        readinessProbe: { httpGet: { path: /healthz, port: 8000 }, initialDelaySeconds: 5 }
        livenessProbe:  { httpGet: { path: /healthz, port: 8000 }, initialDelaySeconds: 5 }
