apiVersion: v1
kind: Service
metadata:
  name: order-svc
  namespace: quickkart
  labels: { app: order-svc }
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path:   /metrics
    prometheus.io/port:   "8000"
spec:
  selector: { app: order-svc }
  ports:
  - port: 8000
    targetPort: 8000
