apiVersion: v1
kind: Namespace
metadata: { name: logging }

---
apiVersion: v1
kind: ConfigMap
metadata: { name: fluent-bit-config, namespace: logging }
data:
  fluent-bit.conf: |
    [SERVICE]  Flush 1  Log_Level info
    [INPUT]    Name tail  Tag kube.*  Path /var/log/containers/*.log  Parser docker
    [OUTPUT]   Name  loki  Match kube.*  Url http://loki.monitoring.svc:3100  Labels job=fluentbit
---
apiVersion: apps/v1
kind: DaemonSet
metadata: { name: fluent-bit, namespace: logging }
spec:
  selector: { matchLabels: { app: fluent-bit } }
  template:
    metadata: { labels: { app: fluent-bit } }
    spec:
      serviceAccountName: fluent-bit
      containers:
      - name: fluent-bit
        image: cr.fluentbit.io/fluent/fluent-bit:3.0
        args: ["-c", "/fluent-bit/etc/fluent-bit.conf"]
        volumeMounts:
        - { name: config, mountPath: /fluent-bit/etc/ }
        - { name: varlog, mountPath: /var/log }
      volumes:
      - { name: config, configMap: { name: fluent-bit-config } }
      - { name: varlog, hostPath: { path: /var/log } }
